export const NAV_LINKS = [
  { href: '/', label: 'Home' },
  { href: '/chi-siamo', label: 'Chi Siamo' },
  { href: '/missione', label: 'Missione' },
  { href: '/progetti', label: 'Progetti' },
  { href: '/eventi', label: 'Eventi' },
  { href: '/diventa-socio', label: 'Diventa Socio' },
  { href: '/sostienici', label: 'Sostienici' },
  { href: '/contatti', label: 'Contatti' },
]

export const IMPACT_STATS = [
  { value: 50, suffix: '+', label: 'Progetti completati', description: 'Iniziative concrete sul territorio' },
  { value: 2000, suffix: '+', label: 'Sostenitori', description: 'Persone che credono nel cambiamento' },
  { value: 500, suffix: '+', label: 'Persone supportate', description: 'Famiglie e individui aiutati' },
  { value: 55, suffix: '+', label: 'Partner', description: 'Enti e organizzazioni alleate' },
  { value: 3000, suffix: '+', label: 'Ore di volontariato', description: 'Ore di volontariato dedicate al cambiamento' },
]

export interface Project {
  id: string
  title: string
  category: string
  categoryColor: string
  tags: string[]
  description: string
  image: string
  href: string
  featured: boolean
  slug: string
  year?: string
  date?: string
  location?: string
  partners?: string[]
  fullDescription?: string[]
  gallery?: { src: string; alt: string }[]
  externalUrl?: string
}

export const PROJECTS: Project[] = [
  {
    id: 'zoo-safari-tour',
    slug: 'zoo-safari-tour',
    title: 'Zoo Safari Tour',
    category: 'Arte',
    categoryColor: 'sky',
    tags: ['arte', 'economia circolare', 'inclusione'],
    year: '2025',
    location: 'Ciampino e Marino',
    description:
      'Sculture animali da biciclette riciclate, un percorso artistico di inclusione ed economia circolare.',
    image: '/images/projects/zoo-safari-tour/scultura-uccello.webp',
    href: '/progetti/zoo-safari-tour',
    featured: true,
    partners: ['Paolo Lo Giudice'],
    fullDescription: [
      'Questa iniziativa, ideata dall\'artista Paolo Lo Giudice, ha trasformato biciclette non più funzionanti in sculture "animali". Il progetto è stato un percorso artistico che ha unito il recupero di materiali altrimenti destinati alla discarica con la valorizzazione delle persone. I ragazzi della Rete Italiana Disabili hanno realizzato le sculture in ferro che sono state poi allestite nei parchi pubblici di Ciampino e Marino. Lavorando insieme, i partecipanti hanno sviluppato nuove energie psico-fisiche e abilità manuali, accrescendo il loro benessere e la loro autostima. L\'intero percorso ha dimostrato che le diverse abilità sono una ricchezza per la crescita della comunità e ha promosso l\'inclusione sociale e l\'accettazione delle diversità.',
    ],
    gallery: [
      { src: '/images/projects/zoo-safari-tour/scultura-uccello.webp', alt: 'Zoo Safari Tour' },
      { src: '/images/projects/zoo-safari-tour/telaio-bici.webp', alt: 'Zoo Safari Tour' },
      { src: '/images/projects/zoo-safari-tour/gruppo-scolaresca.webp', alt: 'Zoo Safari Tour' },
      { src: '/images/projects/zoo-safari-tour/logo.webp', alt: 'Zoo Safari Tour' },
    ],
  },
  {
    id: 'diversamente-divertente',
    slug: 'diversamente-divertente',
    title: 'Diversamente Divertente - V Edizione',
    category: 'Turismo inclusivo',
    categoryColor: 'orange',
    tags: ['turismo inclusivo', 'famiglia', 'sport'],
    year: '2025',
    location: 'Zoomarine, Roma',
    description:
      'Giornata inclusiva a Zoomarine per famiglie con persone con disabilità.',
    image: '/images/projects/diversamente-divertente/cover.jpg',
    href: '/progetti/diversamente-divertente',
    featured: true,
    partners: ['Zoomarine'],
    fullDescription: [
      'La Rete Italiana Disabili e Zoomarine sono lieti di annunciare la quinta edizione di "Diversamente Divertente", un\'occasione unica per trascorrere una giornata indimenticabile all\'insegna del divertimento e dell\'inclusione. L\'ingresso include tutte le attività del parco: dimostrazioni con gli animali, show dei tuffi, show di magia comica, giostre e attrazioni, piscine e acquapark, e il programma "Incontra gli Animali".',
    ],
  },
  {
    id: 'osteopatia-autismo',
    slug: 'osteopatia-autismo',
    title: 'Osteopatia e Autismo',
    category: 'Salute',
    categoryColor: 'magenta',
    tags: ['salute', 'autismo', 'osteopatia'],
    year: '2025',
    location: 'Catania',
    description:
      'Approccio integrato osteopatico per il benessere delle persone nello spettro autistico.',
    image: '/images/projects/osteopatia-autismo/cover.jpg',
    href: '/progetti/osteopatia-autismo',
    featured: true,
    partners: ['Abaton Onlus'],
    fullDescription: [
      'Progetto nato dalla collaborazione tra Rete Italiana Disabili Sicilia e Abaton Onlus. L\'obiettivo è migliorare il benessere delle persone nello spettro autistico attraverso l\'osteopatia, un approccio capace di favorire una maggiore consapevolezza del proprio corpo e di alleviare disagi che influiscono anche sulla sfera emotiva. Le famiglie hanno accolto con entusiasmo questa iniziativa, affidandosi alle mani esperte di uno staff di professionisti locali.',
    ],
  },
  {
    id: 'festival-sport-inclusivo',
    slug: 'festival-sport-inclusivo',
    title: 'Festival dello Sport Inclusivo',
    category: 'Sport',
    categoryColor: 'green',
    tags: ['sport', 'inclusione', 'evento'],
    year: '2024',
    date: '15 dicembre 2024',
    location: 'Roma, Palazzetto dello Sport (Palatiziano)',
    description:
      'Evento sportivo per promuovere l\'inclusione attraverso lo sport e il gioco.',
    image: '/images/projects/festival-sport-inclusivo/logo.webp',
    href: '/progetti/festival-sport-inclusivo',
    featured: false,
    fullDescription: [
      'Il Festival dello Sport Inclusivo è un evento dedicato alla promozione dell\'inclusione sociale attraverso attività sportive accessibili a tutti. L\'edizione del 15 dicembre 2024, al Palazzetto dello Sport (Palatiziano) di Roma, ha coinvolto atleti, famiglie, volontari e cani di assistenza in una giornata di sport, laboratori, boxe, pet therapy e condivisione.',
    ],
    gallery: [
      { src: '/images/projects/festival-sport-inclusivo/logo.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/press-conference.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/poster.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-17.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-368.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-369.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-370.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-371.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-372.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-373.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-374.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-375.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-376.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-377.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-378.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-379.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-380.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-381.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-382.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-383.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-384.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-385.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-386.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-387.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-388.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-389.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-390.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-391.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-392.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-393.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-394.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-395.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-396.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-397.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-398.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-399.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-400.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-401.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-402.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-403.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-404.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-405.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-406.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-407.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-408.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-409.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-410.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-411.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-412.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-413.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-414.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-415.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-416.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-417.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-418.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-419.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-420.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-421.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-422.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-423.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-424.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-425.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-426.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-427.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-428.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-429.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-430.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-431.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-432.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-433.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-434.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-435.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-436.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-437.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-438.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-439.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-440.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-441.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-442.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-443.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-444.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-445.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-446.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-447.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-448.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-449.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-450.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-451.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-452.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-453.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-456.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-457.webp', alt: 'Festival dello Sport Inclusivo' },
      { src: '/images/projects/festival-sport-inclusivo/festival-458.webp', alt: 'Festival dello Sport Inclusivo' },
    ],
  },
  {
    id: 'tirocinio-microsoft',
    slug: 'tirocinio-microsoft',
    title: 'Tirocinio presso Microsoft Italia',
    category: 'Lavoro',
    categoryColor: 'sky',
    tags: ['lavoro', 'formazione', 'inclusione'],
    year: '2025',
    location: 'Milano',
    description:
      'I ragazzi della Rete hanno svolto un tirocinio presso la mensa aziendale di Compass Group Italia.',
    image: '/images/projects/tirocinio-microsoft/servizio-mensa-1.webp',
    href: '/progetti/tirocinio-microsoft',
    featured: true,
    partners: ['Microsoft Italia', 'Compass Group Italia'],
    fullDescription: [
      'Grazie a Microsoft Italia, i nostri ragazzi hanno svolto un tirocinio presso la mensa aziendale di Compass Group Italia. Siamo stati accolti a braccia aperte e abbiamo dimostrato che il nostro servizio non è solo eccellente, ma è fatto con amore, sorriso, empatia e genuinità. Questa esperienza è stata anche una preziosa occasione per presentarci a una grande multinazionale e a tante altre realtà, con la speranza che possano entrare a far parte della nostra rete.',
    ],
    gallery: [
      { src: '/images/projects/tirocinio-microsoft/servizio-mensa-1.webp', alt: 'Tirocinio presso Microsoft Italia' },
      { src: '/images/projects/tirocinio-microsoft/servizio-mensa-2.webp', alt: 'Tirocinio presso Microsoft Italia' },
      { src: '/images/projects/tirocinio-microsoft/pranzo-natale.webp', alt: 'Tirocinio presso Microsoft Italia' },
      { src: '/images/projects/tirocinio-microsoft/abbraccio-cucina.webp', alt: 'Tirocinio presso Microsoft Italia' },
    ],
  },
  {
    id: 'convegno-camera-deputati',
    slug: 'convegno-camera-deputati',
    title: 'Le fragilità nella Società Contemporanea',
    category: 'Advocacy',
    categoryColor: 'blue',
    tags: ['advocacy', 'istituzioni', 'diritti'],
    year: '2025',
    location: 'Roma, Camera dei Deputati',
    description:
      'Partecipazione al convegno alla Camera dei Deputati sulle fragilità sociali.',
    image: '/images/projects/convegno-camera-deputati/cover.jpg',
    href: '/progetti/convegno-camera-deputati',
    featured: false,
    fullDescription: [
      'La Presidente Katiuscia Girolametti ha partecipato al convegno "Le Fragilità nella Società Contemporanea", organizzato da ENAC e dall\'Associazione Nazionale Psicologi presso la Camera dei Deputati. L\'evento ha rappresentato un\'occasione fondamentale per portare all\'attenzione delle istituzioni le sfide che le persone con disabilità affrontano quotidianamente.',
    ],
  },
  {
    id: 'convegno-autismo-catania',
    slug: 'convegno-autismo-catania',
    title: 'Autismo è... Questione di Neurodivergenze',
    category: 'Autismo',
    categoryColor: 'yellow',
    tags: ['autismo', 'convegno', 'neurodivergenza'],
    year: '2025',
    location: 'Catania, Palazzo della Cultura',
    description:
      'Convegno a Catania per approfondire il tema dell\'autismo e della neurodivergenza.',
    image: '/images/projects/convegno-autismo-catania/cover.jpg',
    href: '/progetti/convegno-autismo-catania',
    featured: false,
    fullDescription: [
      'La Rete Italiana Disabili, in collaborazione con il Comune di Catania e con il patrocinio dell\'ARS, ha organizzato un evento al Palazzo della Cultura per approfondire il tema dell\'autismo e della neurodivergenza, con relatori specializzati in psicomotricità funzionale, osteopatia e neurodivergenze.',
    ],
  },
  {
    id: 'salute-mentale-webinar',
    slug: 'salute-mentale-webinar',
    title: 'Approfondiamo la salute mentale',
    category: 'Salute mentale',
    categoryColor: 'magenta',
    tags: ['salute mentale', 'webinar', 'caregiver'],
    year: '2025',
    description:
      'Evento online su caregiver, intelligenza emotiva e supporto tra pari.',
    image: '/images/projects/salute-mentale-webinar/cover.jpg',
    href: '/progetti/salute-mentale-webinar',
    featured: false,
    fullDescription: [
      'Un evento online dedicato alla salute mentale, con discussioni su argomenti cruciali come il ruolo del caregiver, l\'importanza dell\'intelligenza emotiva e il valore dell\'esperto per esperienza. Relatori esperti hanno condiviso le loro conoscenze sull\'Accademia Digitale delle Diversità.',
    ],
  },
  {
    id: 'notte-bianca-volontari',
    slug: 'notte-bianca-volontari',
    title: 'Volontari durante la Notte Bianca',
    category: 'Volontariato',
    categoryColor: 'coral',
    tags: ['volontariato', 'evento', 'comunità'],
    year: '2024',
    description:
      'I nostri volontari attivi durante la Notte Bianca per promuovere l\'inclusione.',
    image: '/images/projects/notte-bianca/cover.jpg',
    href: '/progetti/notte-bianca-volontari',
    featured: false,
    fullDescription: [
      'Progetto di volontariato durante la Notte Bianca, dove i nostri volontari hanno partecipato attivamente per promuovere l\'inclusione sociale e sensibilizzare la comunità sulle tematiche della disabilità.',
    ],
  },
  {
    id: 'festa-mamma-mensa-caritas',
    slug: 'festa-mamma-mensa-caritas',
    title: 'Festa della Mamma alla Mensa Caritas',
    category: 'Solidarietà',
    categoryColor: 'coral',
    tags: ['solidarietà', 'donazioni', 'caritas'],
    year: '2026',
    location: 'Mensa Caritas Colle Oppio, Roma',
    description:
      'Crema spalmabile e cioccolata calda per gli ospiti della Mensa Caritas di Colle Oppio in occasione della Festa della Mamma.',
    image: '/images/projects/festa-mamma-mensa-caritas/locandina.webp',
    href: '/progetti/festa-mamma-mensa-caritas',
    featured: false,
    partners: ['La Casa del Dolce di Ciampino', 'Parrocchia San Luigi Gonzaga di Ciampino', 'Caritas'],
    fullDescription: [
      'Nel progetto "Nessuno è troppo povero per donare un sorriso", che prosegue ininterrottamente da gennaio 2026, abbiamo dedicato l\'iniziativa della Festa della Mamma agli ospiti della Mensa Caritas di Colle Oppio. Un simbolico "prezioso vaso" da 5 kg di crema spalmabile, interamente donato da La Casa del Dolce di Ciampino, ha permesso di destinare i fondi raccolti ad altre necessità caritatevoli. I volontari della Parrocchia di San Luigi Gonzaga di Ciampino, partner costante del progetto, hanno preparato pane e cioccolata calda per i partecipanti, trasformando una donazione in un momento di condivisione e calore umano.',
    ],
  },
  {
    id: 'donazione-rsa-epifania',
    slug: 'donazione-rsa-epifania',
    title: 'Epifania in RSA',
    category: 'Solidarietà',
    categoryColor: 'coral',
    tags: ['solidarietà', 'donazioni', 'RSA'],
    year: '2025',
    location: 'Castelli Romani',
    description:
      'Donazioni per rendere speciale l\'Epifania per gli ospiti di una RSA dei Castelli Romani.',
    image: '/images/projects/donazione-rsa/consegna-panettoni.webp',
    href: '/progetti/donazione-rsa-epifania',
    featured: false,
    partners: ['UGL Trasporto Aereo'],
    fullDescription: [
      'Grazie alla generosa donazione del Coordinamento per le pari opportunità della STC di Roma UGL Trasporto Aereo e a tutte le altre donazioni dei nostri sostenitori, abbiamo reso speciale l\'Epifania per gli ospiti di una RSA dei Castelli Romani.',
    ],
  },
  {
    id: 'trekking-inclusivo',
    slug: 'trekking-inclusivo',
    title: 'Trekking Inclusivo con Joëlette',
    category: 'Sport',
    categoryColor: 'green',
    tags: ['sport', 'natura', 'inclusione'],
    year: '2025',
    description:
      'Escursione in natura con la carrozzina da trekking Joëlette per rendere i sentieri accessibili a tutti.',
    image: '/images/projects/trekking-inclusivo/gruppo-trekking.webp',
    href: '/progetti/trekking-inclusivo',
    featured: false,
    fullDescription: [
      'Una giornata di cammino inclusivo in mezzo alla natura grazie alla Joëlette, la carrozzina monoruota da fuoristrada che permette alle persone con disabilità motoria di percorrere sentieri altrimenti inaccessibili. Volontari, famiglie e partecipanti hanno condiviso l\'esperienza di un\'escursione immersi nel verde, dimostrando che la montagna può essere un luogo di incontro per tutti.',
    ],
    gallery: [
      { src: '/images/projects/trekking-inclusivo/gruppo-trekking.webp', alt: 'Trekking Inclusivo con Joëlette' },
      { src: '/images/projects/trekking-inclusivo/joelette.webp', alt: 'Trekking Inclusivo con Joëlette' },
    ],
  },
  {
    id: 'concorso-letterario-pittorico',
    slug: 'concorso-letterario-pittorico',
    title: 'Concorso Nazionale Letterario Pittorico — 1ª Edizione',
    category: 'Arte',
    categoryColor: 'sky',
    tags: ['arte', 'cultura', 'concorso'],
    year: '2025',
    description:
      'Prima edizione del concorso dedicato a un mondo senza barriere attraverso parole e immagini.',
    image: '/images/projects/concorso-letterario-pittorico/premiazione.webp',
    href: '/progetti/concorso-letterario-pittorico',
    featured: false,
    fullDescription: [
      'La prima edizione del Concorso Nazionale Letterario Pittorico ha visto la partecipazione di numerosi artisti e scrittori che, attraverso le loro opere, hanno raccontato la loro visione di un mondo senza barriere. La cerimonia di premiazione ha celebrato i vincitori con targhe ufficiali, sottolineando il valore dell\'arte come strumento di inclusione.',
    ],
    gallery: [
      { src: '/images/projects/concorso-letterario-pittorico/premiazione.webp', alt: 'Concorso Nazionale Letterario Pittorico — 1ª Edizione' },
      { src: '/images/projects/concorso-letterario-pittorico/targhe.webp', alt: 'Concorso Nazionale Letterario Pittorico — 1ª Edizione' },
    ],
  },
  {
    id: 'campagna-gianduia',
    slug: 'campagna-gianduia',
    title: 'Campagna Gianduia — Una dolcezza che sostiene il coraggio',
    category: 'Solidarietà',
    categoryColor: 'coral',
    tags: ['solidarietà', 'donazioni', 'campagna'],
    year: '2026',
    date: '15 aprile – 15 maggio 2026',
    location: 'Ciampino',
    description:
      'Dona 15€ e ricevi un vasetto di crema artigianale alla Gianduia della Casa del Dolce di Ciampino.',
    image: '/images/home/gianduia/banner.webp',
    href: '/progetti/campagna-gianduia',
    featured: false,
    partners: ['La Casa del Dolce di Ciampino'],
    fullDescription: [
      'Dal 15 aprile al 15 maggio 2026, una donazione di 15 € a Rete Italiana Disabili è stata ricambiata con un vasetto di crema artigianale alla Gianduia, offerto dalla Casa del Dolce di Ciampino. Ogni contributo si è trasformato in sostegno concreto: assistenza, sollievo e progetti di Cura Ricreativa per restituire ai ragazzi il diritto al gioco e ai genitori la forza di continuare.',
    ],
    gallery: [
      { src: '/images/home/gianduia/banner.webp', alt: 'Campagna Gianduia — Una dolcezza che sostiene il coraggio' },
      { src: '/images/home/gianduia/card-1.webp', alt: 'Campagna Gianduia — Una dolcezza che sostiene il coraggio' },
      { src: '/images/home/gianduia/card-2.webp', alt: 'Campagna Gianduia — Una dolcezza che sostiene il coraggio' },
      { src: '/images/home/gianduia/card-3.webp', alt: 'Campagna Gianduia — Una dolcezza che sostiene il coraggio' },
    ],
  },
  {
    id: 'a-tutto-campo-vigna-fiorita-luglio',
    slug: 'a-tutto-campo-vigna-fiorita-luglio',
    title: 'A Tutto Campo',
    category: 'Sport',
    categoryColor: 'green',
    tags: ['sport', 'tennis', 'inclusione'],
    year: '2026',
    date: 'giugno e luglio 2026',
    location: 'Tennis Club Vigna Fiorita, Via Quarto Sant\'Antonio SNC, Ciampino (RM)',
    description:
      'Padel e Tennis senza barriere',
    image: '/images/home/eventi/a_tutto_campo_estate.webp',
    href: '/progetti/a-tutto-campo-vigna-fiorita-luglio',
    featured: false,
    fullDescription: [
      'Tre giornate gratuite di Padel e Tennis con il Tennis Club Vigna Fiorita e il patrocinio del CIP Lazio. I volontari di Rete Italiana Disabili garantiscono accompagnamento e assistenza mirata a partecipanti con disabilità anche complesse. Per prenotare: Cristian Morato, referente sport.',
      'Evento svolto il Tre giornate gratuite — giugno e luglio 2026 presso Tennis Club Vigna Fiorita, Via Quarto Sant\'Antonio SNC, Ciampino (RM).',
    ],
  },
  {
    id: 'alfabetizzazione-digitale-microsoft',
    slug: 'alfabetizzazione-digitale-microsoft',
    title: 'Progetto di Alfabetizzazione Digitale',
    category: 'Formazione',
    categoryColor: 'blue',
    tags: ['formazione', 'digitale', 'inclusione'],
    year: '2026',
    date: 'Giovedì 3 luglio 2026',
    location: 'Sede Microsoft, Viale Avignone 10, Roma EUR (parcheggio interno accessibile)',
    description:
      'La tecnologia al servizio delle famiglie',
    image: '/images/home/eventi/alfabetizzazione-digitale.webp',
    href: '/progetti/alfabetizzazione-digitale-microsoft',
    featured: false,
    fullDescription: [
      'Nasce il supporto digitale gratuito di Rete Italiana Disabili: un vero e proprio corso base di PC e alfabetizzazione digitale, pensato per chi vuole muovere i primi passi o ha bisogno di imparare a gestire le piccole commissioni di ogni giorno. Seguiranno altri incontri da remoto.',
      'Evento svolto il Giovedì 3 luglio 2026 presso Sede Microsoft, Viale Avignone 10, Roma EUR (parcheggio interno accessibile).',
    ],
  },
  {
    id: 'in-campo-inclusione-catania',
    slug: 'in-campo-inclusione-catania',
    title: 'In Campo per l\'Inclusione',
    category: 'Sport',
    categoryColor: 'green',
    tags: ['sport', 'inclusione', 'Sicilia'],
    year: '2026',
    date: 'Giovedì 18 giugno 2026',
    location: 'City Sports Club, Via Santa Sofia, 95123 Catania (CT)',
    description:
      'Sport e inclusione al City Sports Club',
    image: '/images/home/eventi/in-campo-inclusione.webp',
    href: '/progetti/in-campo-inclusione-catania',
    featured: false,
    fullDescription: [
      'Una giornata di sport e inclusione al City Sports Club di Catania, promossa da Rete Italiana Disabili Sicilia insieme al City Sports Club e all\'associazione "La voce e le parole". Lo sport come strumento di incontro, crescita e abbattimento delle barriere.',
      'Evento svolto il Giovedì 18 giugno 2026 presso City Sports Club, Via Santa Sofia, 95123 Catania (CT).',
    ],
  },
  {
    id: 'come-ti-senti-acireale',
    slug: 'come-ti-senti-acireale',
    title: 'Come ti senti nel tuo corpo?',
    category: 'Benessere',
    categoryColor: 'magenta',
    tags: ['benessere', 'salute mentale', 'Sicilia'],
    year: '2026',
    date: 'maggio – giugno 2026',
    location: 'Osteorganiclinic, Via Cervo 46F, Acireale (CT)',
    description:
      'Percorso di consapevolezza per ragazzi e genitori',
    image: '/images/home/eventi/come-ti-senti.webp',
    href: '/progetti/come-ti-senti-acireale',
    featured: false,
    fullDescription: [
      'Un percorso per capire e prendersi cura di sé, che aiuta bambini e genitori a conoscere il corpo, le sensazioni, le emozioni e le relazioni attraverso quattro incontri pratici e un incontro introduttivo dedicato anche ai genitori. Promosso da Rete Italiana Disabili Sicilia.',
      'Evento svolto il Da maggio a giugno 2026 presso Osteorganiclinic, Via Cervo 46F, Acireale (CT).',
    ],
  },
  {
    id: 'a-tutto-campo-vigna-fiorita',
    slug: 'a-tutto-campo-vigna-fiorita',
    title: 'A Tutto Campo',
    category: 'Sport',
    categoryColor: 'green',
    tags: ['sport', 'tennis', 'inclusione'],
    year: '2026',
    date: 'maggio e giugno 2026',
    location: 'Tennis Club Vigna Fiorita, Via Quarto Sant\'Antonio SNC, Ciampino (RM)',
    description:
      'Padel e Tennis senza barriere',
    image: '/images/home/eventi/a_tutto_campo.webp',
    href: '/progetti/a-tutto-campo-vigna-fiorita',
    featured: false,
    fullDescription: [
      'Tre giornate gratuite di Padel e Tennis con il Tennis Club Vigna Fiorita e il patrocinio del CIP Lazio. Supporto tecnico di Monia Franchi; i volontari di Rete Italiana Disabili garantiscono accompagnamento e assistenza mirata a partecipanti con disabilità anche complesse.',
      'Evento svolto il Tre giornate — maggio e giugno 2026 presso Tennis Club Vigna Fiorita, Via Quarto Sant\'Antonio SNC, Ciampino (RM).',
    ],
  },
  {
    id: 'nessuno-troppo-povero-caritas-giugno',
    slug: 'nessuno-troppo-povero-caritas-giugno',
    title: 'Nessuno è troppo povero per donare un sorriso',
    category: 'Solidarietà',
    categoryColor: 'coral',
    tags: ['solidarietà', 'volontariato', 'caritas'],
    year: '2026',
    date: 'Domenica 7 giugno 2026',
    location: 'Mensa Caritas Colle Oppio, Roma',
    description:
      'Mattinata solidale alla Mensa Caritas',
    image: '/images/home/eventi/nessuno-troppo-povero-caritas.webp',
    href: '/progetti/nessuno-troppo-povero-caritas-giugno',
    featured: false,
    fullDescription: [
      'Una nuova tappa del progetto "Nessuno è troppo povero per donare un sorriso", che prosegue ininterrottamente da gennaio 2026. I volontari di Rete Italiana Disabili hanno portato un momento di calore e condivisione agli ospiti della Mensa Caritas di Colle Oppio.',
      'Evento svolto il Domenica 7 giugno 2026 presso Mensa Caritas Colle Oppio, Roma.',
    ],
  },
  {
    id: 'pluralita-diversita-roma',
    slug: 'pluralita-diversita-roma',
    title: 'Pluralità Diversità – be inclusive',
    category: 'Arte',
    categoryColor: 'sky',
    tags: ['arte', 'cultura', 'inclusione'],
    year: '2026',
    date: 'Giovedì 4 giugno 2026',
    location: 'Galleria d\'Arte – Centro Interculturale Art Studio, Via della Lungara 43, Roma',
    description:
      'Collettiva d\'arte per l\'inclusione',
    image: '/images/home/eventi/pluralita-diversita.webp',
    href: '/progetti/pluralita-diversita-roma',
    featured: false,
    fullDescription: [
      'Una collettiva d\'arte dedicata alla pluralità e alla diversità, promossa da B-HOP Magazine. Rete Italiana Disabili ha partecipato con il Progetto Zoo Safari Tour, raccontato dalla storica dell\'arte Silvia Filippi, insieme alle opere di numerosi artisti. La serata si è conclusa con un aperitivo solidale.',
      'Evento svolto il Giovedì 4 giugno 2026 presso Galleria d\'Arte – Centro Interculturale Art Studio, Via della Lungara 43, Roma.',
    ],
  },
  {
    id: 'prenditi-cura-di-te-catania',
    slug: 'prenditi-cura-di-te-catania',
    title: 'Prenditi cura di te',
    category: 'Benessere',
    categoryColor: 'magenta',
    tags: ['benessere', 'caregiver', 'salute mentale'],
    year: '2026',
    date: 'Venerdì 29 maggio 2026',
    location: 'Piazza Scammacca 9, 95131 Catania (CT)',
    description:
      'Percorso di benessere psicologico per caregiver',
    image: '/images/home/eventi/prenditi_cura_di_te.webp',
    href: '/progetti/prenditi-cura-di-te-catania',
    featured: false,
    fullDescription: [
      'Sei incontri promossi da Rete Italiana Disabili Sicilia con il Comune di Catania: cura di sé, identità genitoriale, meditazione, condivisione e improvvisazione teatrale. Alle 19:30 “pillole di vino” con ONAV Catania e brindisi offerto da Piazza Scammacca.',
      'Evento svolto il Venerdì 29 maggio 2026 presso Piazza Scammacca 9, 95131 Catania (CT).',
    ],
  },
  {
    id: 'festa-primavera-castel-gandolfo',
    slug: 'festa-primavera-castel-gandolfo',
    title: 'La Grande Festa di Primavera',
    category: 'Inclusione',
    categoryColor: 'blue',
    tags: ['inclusione', 'natura', 'famiglia'],
    year: '2026',
    date: 'Domenica 24 maggio 2026',
    location: 'Tenuta Mosaico, Castel Gandolfo (RM)',
    description:
      'More Love, Less Barriers — Noi Siamo Rete',
    image: '/images/home/eventi/festa_della_primavera.webp',
    href: '/progetti/festa-primavera-castel-gandolfo',
    featured: false,
    fullDescription: [
      'Una giornata di gioia, natura e inclusione: laboratorio di riciclo con RiArtEco, digitalizzazione inclusiva con LoveMeToo, percorsi nel verde e incontro con i cavalli con Green Light APS, laboratorio pizza e musica dal vivo con JSAX Events. Ingresso gratuito con prenotazione obbligatoria.',
      'Evento svolto il Domenica 24 maggio 2026 presso Tenuta Mosaico, Castel Gandolfo (RM).',
    ],
    gallery: [
      { src: '/images/home/eventi/festa_della_primavera.webp', alt: 'La Grande Festa di Primavera' },
      { src: '/images/home/eventi/festa_della_primavera_programma_dettagliato.webp', alt: 'La Grande Festa di Primavera' },
    ],
  },
  {
    id: 'partita-solidale-ciampino',
    slug: 'partita-solidale-ciampino',
    title: 'Partita Solidale',
    category: 'Sport',
    categoryColor: 'green',
    tags: ['sport', 'calcio', 'solidarietà'],
    year: '2026',
    date: 'Mercoledì 15 maggio 2026',
    location: 'Centro Sportivo, Via Icaro 1, Ciampino (RM)',
    description:
      'Il calcio come ponte verso l\'inclusione',
    image: '/images/home/eventi/15_maggio_partita_solidale.webp',
    href: '/progetti/partita-solidale-ciampino',
    featured: false,
    fullDescription: [
      'A.S.D. Colberoma Academy e Rete Italiana Disabili insieme per una serata di sport e fratellanza, con il patrocinio della Parrocchia Gesù Divino Operaio. Dopo il fischio finale, tutti a tavola per il tradizionale Terzo Tempo.',
      'Evento svolto il Mercoledì 15 maggio 2026 presso Centro Sportivo, Via Icaro 1, Ciampino (RM).',
    ],
  },
]

export const EVENTS = [
  {
    id: 'a-tutto-campo-speciale-serale',
    title: 'A Tutto Campo – Speciale Serale',
    eyebrow: 'Padel inclusivo e giro pizza a bordo campo',
    date: '2026-07-28',
    dateLabel: 'Martedì 28 luglio 2026',
    time: 'Ore 18:00–19:30',
    location: "Tennis Club Vigna Fiorita, Via Quarto Sant'Antonio SNC, Ciampino (RM)",
    type: 'Sport',
    description:
      'Una speciale serata A Tutto Campo insieme al Tennis Club Vigna Fiorita: padel inclusivo e giro pizza a bordo campo, con pizza, fritti, bibita e dolce. Quota intera 20 € tutto compreso, bambini dai 3 ai 6 anni 10 €, gratis i piccolissimi sotto i 3 anni. Partecipando darai anche un piccolo e prezioso contributo a sostegno delle attività inclusive dell\'Associazione.',
    image: '/images/home/eventi/a-tutto-campo-speciale-serale.webp',
    imageAlt:
      "Locandina Speciale Serale A Tutto Campo: padel inclusivo e giro pizza a bordo campo al Tennis Club Vigna Fiorita di Ciampino, martedì 28 luglio 2026 dalle 18:00",
    featured: true,
    video: '/videos/a-tutto-campo-speciale-serale.mp4',
    videoCaption: 'La testimonianza che ti invita a partecipare',
    ctaPrimary: { label: 'Prenota via WhatsApp', href: 'https://wa.me/393332967651' },
    ctaSecondary: { label: 'Oppure 392 627 1434', href: 'https://wa.me/393926271434' },
    upcoming: true,
  },
  {
    id: 'a-tutto-campo-padel-inclusivo',
    title: 'A Tutto Campo – Padel Inclusivo',
    eyebrow: 'Un corso di padel inclusivo per tutti',
    date: '2026-09-01',
    dateLabel: 'Da settembre 2026',
    time: 'Due sessioni a settimana, 1 ora ciascuna',
    location: "Tennis Club Vigna Fiorita, Via Quarto Sant'Antonio SNC, Ciampino (RM)",
    type: 'Sport',
    description:
      'Dalla collaborazione tra Rete Italiana Disabili e il Tennis Club Vigna Fiorita nasce un vero e proprio corso di padel inclusivo. Da settembre, due sessioni a settimana di un\'ora ciascuna, con educatori e maestri federali di padel pronti a far vivere ai partecipanti questa fantastica esperienza: non solo tante agevolazioni, ma un percorso continuativo e accessibile a tutti. Vuoi partecipare all\'iniziativa o diventare nostro sponsor? Contattaci.',
    image: '/images/home/eventi/a-tutto-campo-padel/card-1.webp',
    imageAlt:
      'A Tutto Campo – Padel Inclusivo: corso di padel inclusivo dalla collaborazione tra Rete Italiana Disabili e Tennis Club Vigna Fiorita',
    featured: false,
    gallery: [
      { src: '/images/home/eventi/a-tutto-campo-padel/card-2.webp', alt: 'A Tutto Campo – Padel Inclusivo — card 2' },
      { src: '/images/home/eventi/a-tutto-campo-padel/card-3.webp', alt: 'A Tutto Campo – Padel Inclusivo — card 3' },
      { src: '/images/home/eventi/a-tutto-campo-padel/card-4.webp', alt: 'A Tutto Campo – Padel Inclusivo — card 4' },
      { src: '/images/home/eventi/a-tutto-campo-padel/card-5.webp', alt: 'A Tutto Campo – Padel Inclusivo — card 5' },
    ],
    ctaPrimary: { label: 'Scrivi su WhatsApp', href: 'https://wa.me/393332967651' },
    ctaSecondary: { label: 'Diventa sponsor', href: '/sponsor' },
    upcoming: true,
  },
]

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Marco Ferretti',
    role: 'Padre di Lorenzo, 14 anni',
    text: 'Grazie a Rete Italiana Disabili ETS abbiamo trovato il supporto che cercavamo per Lorenzo. Non ci siamo mai sentiti soli in questo percorso.',
    avatar: '/images/testimonials/marco.jpg',
  },
  {
    id: '2',
    name: 'Giulia Romano',
    role: 'Persona con disabilità visiva',
    text: 'Il progetto di accessibilità digitale mi ha cambiato la vita. Oggi lavoro in un\'azienda tech grazie alle competenze acquisite.',
    avatar: '/images/testimonials/giulia.jpg',
  },
  {
    id: '3',
    name: 'Dott.ssa Annamaria Costa',
    role: 'Dirigente scolastica',
    text: 'Abbiamo partecipato al programma Scuola Inclusiva e la nostra scuola è diventata un riferimento per l\'inclusione nella provincia.',
    avatar: '/images/testimonials/anna.jpg',
  },
]

export const SPONSORS = [
  { name: 'Danny Kaye', logo: '/images/sponsors/danny-kaye.webp' },
  { name: 'Pompi, il regno del tiramisù', logo: '/images/sponsors/pompi.webp' },
  { name: 'Grossi Immobiliare', logo: '/images/sponsors/grossi-immobiliare.webp' },
  { name: 'Fulcro Bistrot', logo: '/images/sponsors/fulcro-bistrot.webp' },
  { name: 'ONAV', logo: '/images/sponsors/onav.webp' },
  { name: 'Theatrike', logo: '/images/sponsors/theatrike.webp' },
  { name: 'City Wellness Club', logo: '/images/sponsors/city-wellness.webp' },
  { name: "L'atelier del movimento", logo: '/images/sponsors/atelier-movimento.webp' },
  { name: 'Chi.pia', logo: '/images/sponsors/chipia.webp' },
  { name: 'Manitas Lab Creativo', logo: '/images/sponsors/manitas.webp' },
  { name: 'Giungi', logo: '/images/sponsors/giungi.webp' },
  { name: 'AITO – Associazione Italiana Terapisti Occupazionali', logo: '/images/sponsors/aito.webp' },
  { name: 'Ambasciata di Francia in Italia', logo: '/images/sponsors/ambasciata-francia.webp' },
  { name: 'Associazione Nazionale Carabinieri', logo: '/images/sponsors/anc.webp' },
  { name: 'Assemblea Regionale Siciliana', logo: '/images/sponsors/assemblea-regionale-siciliana.webp' },
  { name: 'Athletica Vaticana', logo: '/images/sponsors/athletica-vaticana.webp' },
  { name: 'Baskin', logo: '/images/sponsors/baskin.webp' },
  { name: 'Centro Città Holiday Apartment', logo: '/images/sponsors/centro-citta-holiday.webp' },
  { name: 'City Sport Club', logo: '/images/sponsors/city-sport-club.webp' },
  { name: 'Comitato Italiano Paralimpico Lazio', logo: '/images/sponsors/comitato-paralimpico-lazio.webp' },
  { name: 'Comune di Ciampino', logo: '/images/sponsors/comune-ciampino.webp' },
  { name: 'Comune di Marino', logo: '/images/sponsors/comune-marino.webp' },
  { name: 'CONI – Comitato Regionale Lazio', logo: '/images/sponsors/coni.webp' },
  { name: 'Croce Rossa Italiana', logo: '/images/sponsors/croce-rossa-italiana.webp' },
  { name: 'CSV Lazio – Centro di Servizio per il Volontariato', logo: '/images/sponsors/csv-lazio.webp' },
  { name: 'DEM Supermercati', logo: '/images/sponsors/dem-supermercati.webp' },
  { name: "Dicastero per la Cultura e l'Educazione", logo: '/images/sponsors/dicastero-cultura-educazione.webp' },
  { name: 'ENAC', logo: '/images/sponsors/enac.webp' },
  { name: 'Etica e Autismo APS', logo: '/images/sponsors/etica-e-autismo.webp' },
  { name: 'FAB – Pizza, Burger & Wine Bar', logo: '/images/sponsors/fab.webp' },
  { name: 'Fantasia & Bellezza', logo: '/images/sponsors/fantasia-e-bellezza.webp' },
  { name: 'Federazione Pugilistica Italiana', logo: '/images/sponsors/federazione-pugilistica.webp' },
  { name: 'FISDIR – Federazione Italiana Sport Paralimpici degli Intellettivo Relazionali', logo: '/images/sponsors/fisdir.webp' },
  { name: 'FITET – Federazione Italiana Tennistavolo', logo: '/images/sponsors/fitet.webp' },
  { name: 'Fondazione The Bridge', logo: '/images/sponsors/fondazione-the-bridge.webp' },
  { name: 'Green Light', logo: '/images/sponsors/green-light.webp' },
  { name: 'JSax Events', logo: '/images/sponsors/jsax.webp' },
  { name: 'La Banca delle Visite', logo: '/images/sponsors/la-banca-delle-visite.webp' },
  { name: 'La Voce e le Parole APS', logo: '/images/sponsors/la-voce-e-le-parole.webp' },
  { name: "McDonald's", logo: '/images/sponsors/mcdonalds.webp' },
  { name: 'Ambasciata del Messico in Italia', logo: '/images/sponsors/mexico.webp' },
  { name: 'Municipio VI di Roma', logo: '/images/sponsors/municipio-vi-roma.webp' },
  { name: 'Occupiamocene APS', logo: '/images/sponsors/occupiamocene.webp' },
  { name: 'Panificio Briciole di Piazza', logo: '/images/sponsors/panificio-briciole-di-piazza.webp' },
  { name: 'Parrocchia Gesù Divino Operaio – Ciampino', logo: '/images/sponsors/parrocchia-gesu-divino-operaio.webp' },
  { name: 'Regione Lazio', logo: '/images/sponsors/regione-lazio.webp' },
  { name: 'RiArtEco', logo: '/images/sponsors/riareteco.webp' },
  { name: 'Sport e Salute', logo: '/images/sponsors/sport-e-salute.webp' },
  { name: 'Città di Catania', logo: '/images/sponsors/spqc.webp' },
  { name: 'SSD Alice City', logo: '/images/sponsors/ssd-alice-city.webp' },
  { name: 'Tacchi e Sapori', logo: '/images/sponsors/tacchi-e-sapori.webp' },
  { name: 'Tenuta Mosaico', logo: '/images/sponsors/tenuta-mosaico.webp' },
  { name: 'UDICON', logo: '/images/sponsors/udicon.webp' },
  { name: 'Unione Invalidi Civili', logo: '/images/sponsors/unione-invalidi-civili.webp' },
  { name: 'Via Francigena', logo: '/images/sponsors/via-francigena.webp' },
  { name: 'Vigili del Fuoco', logo: '/images/sponsors/vigili-del-fuoco.webp' },
  { name: 'Vita Via Est', logo: '/images/sponsors/vita-via-est.webp' },
]

export const PARTNERS = [
  { name: 'Ministero del Lavoro', href: '#' },
  { name: 'INPS', href: '#' },
  { name: 'Fondazione Cariplo', href: '#' },
  { name: 'Regione Lombardia', href: '#' },
  { name: 'Comune di Roma', href: '#' },
  { name: 'ANMIL', href: '#' },
  { name: 'Fondazione Banco di Napoli', href: '#' },
  { name: 'Università La Sapienza', href: '#' },
]

export const MISSION_CARDS = [
  {
    title: 'Inclusione',
    icon: 'users',
    color: 'sky',
    description:
      'Promuoviamo una società dove ogni persona, indipendentemente dalle proprie abilità, possa partecipare pienamente alla vita sociale, culturale e lavorativa.',
  },
  {
    title: 'Diritti',
    icon: 'shield',
    color: 'blue',
    description:
      'Difendiamo i diritti delle persone con disabilità, monitorando l\'applicazione delle leggi e proponendo miglioramenti legislativi concreti.',
  },
  {
    title: 'Partecipazione',
    icon: 'handshake',
    color: 'green',
    description:
      'Costruiamo reti tra associazioni, istituzioni, aziende e cittadini per moltiplicare l\'impatto delle azioni a favore dell\'inclusione.',
  },
]

export const WHO_WE_HELP = [
  {
    title: 'Persone con Disabilità',
    description: 'Supporto diretto, formazione, orientamento ai servizi e difesa dei diritti.',
    icon: 'accessibility',
    color: 'blue',
    href: '/chi-siamo#persone',
  },
  {
    title: 'Famiglie',
    description: 'Risorse, sportelli di ascolto e comunità di supporto per i caregiver.',
    icon: 'home',
    color: 'green',
    href: '/chi-siamo#famiglie',
  },
  {
    title: 'Istituzioni',
    description: 'Consulenza, partnership e strumenti per politiche di inclusione efficaci.',
    icon: 'building',
    color: 'orange',
    href: '/chi-siamo#istituzioni',
  },
  {
    title: 'Volontari',
    description: 'Opportunità di crescita personale e professionale attraverso l\'impegno civile.',
    icon: 'heart',
    color: 'coral',
    href: '/chi-siamo#volontari',
  },
]

export const PROJECT_CATEGORIES = [
  'Tutti',
  '2026',
  '2025',
  '2024',
]
